language: node_js

node_js:
  - '0.10'

before_script:
  - 'gem install sass --version "=3.2.12"'
  - 'gem install compass --version "=0.12.2"'
  - 'npm install --quiet -g bower grunt-cli karma'
  - 'npm install'
  - 'bower install'

branches:
  only:
    - master

script: grunt ci